name: CI/CD Django + React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_VPS }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/TutorMove
            git reset --hard
            git pull origin main
            source backend/venv/bin/activate
            pip install -r backend/requirements.txt
            python backend/manage.py migrate --noinput
            python backend/manage.py collectstatic --noinput
            cd frontend
            npm install
            npm run build
            sudo systemctl restart tutormove
            sudo systemctl restart tutormove-rqworker
            sudo systemctl restart nginx
